# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlacesNear' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlacesNear

  target 'PlacesNearTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlacesNearUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Alamofire'
  pod 'SnapKit'
  pod 'HandyJSON', '4.0.0-beta.1'
  pod 'RxSwift'

  pod 'BaiduMapKit'
end
